package com.lanou.entity;

public class AuthUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_employee.SN
     *
     * @mbg.generated Thu Jan 25 15:18:06 CST 2018
     */
    private Integer SN;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_employee.POSITION_ID
     *
     * @mbg.generated Thu Jan 25 15:18:06 CST 2018
     */
    private Integer POSITION_ID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_employee.DEPARTMENT_ID
     *
     * @mbg.generated Thu Jan 25 15:18:06 CST 2018
     */
    private Integer DEPARTMENT_ID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_employee.NAME
     *
     * @mbg.generated Thu Jan 25 15:18:06 CST 2018
     */
    private String NAME;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_employee.PASSWORD
     *
     * @mbg.generated Thu Jan 25 15:18:06 CST 2018
     */
    private String PASSWORD;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_employee.STATUS
     *
     * @mbg.generated Thu Jan 25 15:18:06 CST 2018
     */
    private String STATUS;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_employee.SN
     *
     * @return the value of sys_employee.SN
     *
     * @mbg.generated Thu Jan 25 15:18:06 CST 2018
     */
    public Integer getSN() {
        return SN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_employee.SN
     *
     * @param SN the value for sys_employee.SN
     *
     * @mbg.generated Thu Jan 25 15:18:06 CST 2018
     */
    public void setSN(Integer SN) {
        this.SN = SN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_employee.POSITION_ID
     *
     * @return the value of sys_employee.POSITION_ID
     *
     * @mbg.generated Thu Jan 25 15:18:06 CST 2018
     */
    public Integer getPOSITION_ID() {
        return POSITION_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_employee.POSITION_ID
     *
     * @param POSITION_ID the value for sys_employee.POSITION_ID
     *
     * @mbg.generated Thu Jan 25 15:18:06 CST 2018
     */
    public void setPOSITION_ID(Integer POSITION_ID) {
        this.POSITION_ID = POSITION_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_employee.DEPARTMENT_ID
     *
     * @return the value of sys_employee.DEPARTMENT_ID
     *
     * @mbg.generated Thu Jan 25 15:18:06 CST 2018
     */
    public Integer getDEPARTMENT_ID() {
        return DEPARTMENT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_employee.DEPARTMENT_ID
     *
     * @param DEPARTMENT_ID the value for sys_employee.DEPARTMENT_ID
     *
     * @mbg.generated Thu Jan 25 15:18:06 CST 2018
     */
    public void setDEPARTMENT_ID(Integer DEPARTMENT_ID) {
        this.DEPARTMENT_ID = DEPARTMENT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_employee.NAME
     *
     * @return the value of sys_employee.NAME
     *
     * @mbg.generated Thu Jan 25 15:18:06 CST 2018
     */
    public String getNAME() {
        return NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_employee.NAME
     *
     * @param NAME the value for sys_employee.NAME
     *
     * @mbg.generated Thu Jan 25 15:18:06 CST 2018
     */
    public void setNAME(String NAME) {
        this.NAME = NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_employee.PASSWORD
     *
     * @return the value of sys_employee.PASSWORD
     *
     * @mbg.generated Thu Jan 25 15:18:06 CST 2018
     */
    public String getPASSWORD() {
        return PASSWORD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_employee.PASSWORD
     *
     * @param PASSWORD the value for sys_employee.PASSWORD
     *
     * @mbg.generated Thu Jan 25 15:18:06 CST 2018
     */
    public void setPASSWORD(String PASSWORD) {
        this.PASSWORD = PASSWORD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_employee.STATUS
     *
     * @return the value of sys_employee.STATUS
     *
     * @mbg.generated Thu Jan 25 15:18:06 CST 2018
     */
    public String getSTATUS() {
        return STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_employee.STATUS
     *
     * @param STATUS the value for sys_employee.STATUS
     *
     * @mbg.generated Thu Jan 25 15:18:06 CST 2018
     */
    public void setSTATUS(String STATUS) {
        this.STATUS = STATUS;
    }
}