package com.lanou.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import com.lanou.entity.AuthUser;
public interface AuthUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_employee
     *
     * @mbg.generated Thu Jan 25 15:18:06 CST 2018
     */
    int deleteByPrimaryKey(Integer SN);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_employee
     *
     * @mbg.generated Thu Jan 25 15:18:06 CST 2018
     */
    int insert(AuthUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_employee
     *
     * @mbg.generated Thu Jan 25 15:18:06 CST 2018
     */
    int insertSelective(AuthUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_employee
     *
     * @mbg.generated Thu Jan 25 15:18:06 CST 2018
     */
    AuthUser selectByPrimaryKey(Integer SN);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_employee
     *
     * @mbg.generated Thu Jan 25 15:18:06 CST 2018
     */
    int updateByPrimaryKeySelective(AuthUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_employee
     *
     * @mbg.generated Thu Jan 25 15:18:06 CST 2018
     */
    int updateByPrimaryKey(AuthUser record);
    
    
    List<AuthUser> selectAll();
    
}